
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 17 17:42:47 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int LCBR = 13;
  public static final int LTE = 38;
  public static final int STR = 5;
  public static final int UMINUS = 45;
  public static final int INTEGER = 46;
  public static final int SEMI = 10;
  public static final int CONTINUE = 20;
  public static final int INT = 4;
  public static final int MINUS = 32;
  public static final int STATIC = 27;
  public static final int LT = 36;
  public static final int LP = 15;
  public static final int COMMA = 11;
  public static final int CLASS = 30;
  public static final int RP = 16;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 33;
  public static final int QUOTE = 49;
  public static final int ASSIGN = 9;
  public static final int IF = 24;
  public static final int THIS = 28;
  public static final int ID = 47;
  public static final int DOT = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int LAND = 43;
  public static final int RCBR = 14;
  public static final int LB = 17;
  public static final int RETURN = 21;
  public static final int EQUAL = 40;
  public static final int TRUE = 6;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int RB = 18;
  public static final int LOR = 44;
  public static final int NULL = 8;
  public static final int MOD = 35;
  public static final int BREAK = 19;
  public static final int VOID = 3;
  public static final int GTE = 39;
  public static final int ELSE = 25;
  public static final int WHILE = 23;
  public static final int NEQUAL = 41;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 29;
  public static final int LNEG = 42;
  public static final int FALSE = 7;
  public static final int GT = 37;
  public static final int LENGTH = 26;
}

